### PR TITLE
use "ember-new-computed" to polyfill Ember's new CP syntax

### PR DESCRIPTION
**Pull request by salzhrani**
currently throwing deprecations on 1.12 beta

### CODE REVIEW

**Comment by miguelcobain** [comment]
Thanks!

**Comment by al3x-edge** [comment]
:+1: Was just looking to fix this. Thanks @salzhrani

**Comment by salzhrani** [comment]
You are welcome ... ember-paper may need some CP love.

**Comment by miguelcobain** [comment]
You mean ember-selectize? :)

**Comment by al3x-edge** [comment]
Maybe this one https://github.com/miguelcobain/ember-paper? Thanks again though. Including @miguelcobain for cutting a release.

**Comment by sandstrom** [comment]
I think change broke the plugin on node 0.12. Works when I downgrade to `0.3.0`.

> Uncaught SyntaxError: Unexpected token .

(caused by some new ES6 syntax used)

**Pull request merged**
