### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Romanior**
plugins values should have space after comma.

### CODE REVIEW

**Comment by miguelcobain** [comment]
@Romanior this is a bug. It shouldn't require a space after the comma.

The bug is here: https://github.com/miguelcobain/ember-cli-selectize/blob/master/addon%2Fcomponents%2Fember-selectize.js#L199

The split should be done using `','` and not `', '`. We have `trim()` after this for this very reason.
Can fix that, add a changelog entry for 0.4.4 and PR, please?

**Comment by Romanior** [comment]
sure I can do it, a bit later though, it is hard to figure out which part is a wrong one :)

**Comment by miguelcobain** [comment]
I've linked the line which needs to be changed.
Basically replace `', '` with `','`.

**Comment by miguelcobain** [comment]
And adding an entry to the CHANGELOG, please. :)

**Pull request closed without merging**
