### PR TITLE
Allow the ability to set searchField

### PR DESCRIPTION
**Pull request by SirZach**
#64

### CODE REVIEW

**Comment by miguelcobain** [comment]
Since there isn't an included `array` helper, I think it would be nice to allow `searchField="label,value"`?

Also, I'm not really into this option in the ember-cli-selectize context.
Selectize docs mention:
> An array of property names to analyze when filtering options.

But how exactly does selectize "analyze" these options? Sorry, but I'm completely out of time and with a bit of help I could review this faster. Thanks!

**Comment by SirZach** [comment]
@miguelcobain there are options these days for people to get arrays like `ember-composable-helpers` or for them to define there own simple array helper or even have a property on a controller that's an array.

I'm not entirely sure how selectize does their analysis. I just know that if I give it an array like `['label', 'value']` it allows for searching against the group title and the individual values within a group.

**Comment by miguelcobain** [comment]
Understood.
I'm aware of those helpers. However, we already do such a thing in the `plugins` property.

In any case, if someone needs that, he/she can iterate and PR that.
Thanks.

**Comment by SirZach** [comment]
Thanks for the merge. Agreed that it can be iterated on to allow for comma separated values.

**Pull request merged**
