### PR TITLE
Fix template and view rendering

### PR DESCRIPTION
**Pull request by lan0**
In current Ember versions you can pass an object as a controller to a view.

### CODE REVIEW

**Comment by felixkiss** [comment]
:+1:

**Comment by miguelcobain** [comment]
Is template and view rendering working now?
We need tests for this. :pray:

**Comment by lan0** [comment]
An example test (doesn't do anything because it doesn't run):
```js
test('option template gets rendered', function(assert) {
  var component = this.subject();
  var content = exampleObjectContent();

  var template = Ember.Handlebars.compile('Hi, {{label}}');
  this.container.register('template:test', template);

  Ember.run(function() {
    component.set('content', content);
    component.set('optionValuePath', 'id');
    component.set('optionLabelPath', 'label');
    component.set('optionTemplate', 'test');
  });
  this.render();
});
```

And the error:
```
Cannot call `compile` without the template compiler loaded.
Please load `ember-template-compiler.js` prior to calling `compile`.
```

If `app.import('bower_components/ember/ember-template-compiler.js');` is included in the Brocfile (see https://github.com/emberjs/ember.js/issues/10265), then it fails with
```
TypeError: Cannot set property '_elementInserted' of null`.
```

Don't really know how to fix this, maybe someone can chime in?

**Comment by miguelcobain** [comment]
Probably related with #56.

**Comment by felixkiss** [comment]
Tried to write an acceptance test, but it only succeeds in Chrome (run by `ember test --server`) and fails in PhantomJS.

Output for acceptance test:
```
Acceptance | ember selectize test: template specified by optionTemplate is used
    ✘ TypeError: 'undefined' is not a function (evaluating 'renderFunction.bind(this.get('targetObject'))')
         expected true
    ✘ afterEach failed on template specified by optionTemplate is used: 'undefined' is not an object (evaluating 'this._selectize.destroy')
```

Output for failing unit test:
```
Unit | Component | ember-selectize: template specified by optionTemplate is used
    ✘ Died on test #1     at http://localhost:7357/assets/test-support.js:2666
        at test (http://localhost:7357/assets/test-support.js:1644)
        at http://localhost:7357/assets/dummy.js:1219
        at http://localhost:7357/assets/vendor.js:150
        at tryFinally (http://localhost:7357/assets/vendor.js:30)
        at http://localhost:7357/assets/vendor.js:156
        at http://localhost:7357/assets/test-loader.js:29
        at http://localhost:7357/assets/test-loader.js:21
        at http://localhost:7357/assets/test-loader.js:40
        at http://localhost:7357/assets/test-support.js:5438: 'null' is not an object (evaluating 'views[i]._elementInserted = true')
```

Works in Chrome though ...

**Comment by lan0** [comment]
The reason the acceptance test fails in PhantomJS seems to be that `optionFunction` is set in `application.hbs` for one of the components in the dummy app. This leaks to the component that uses the template in PhantomJS for whatever reason. If you remove this option, the tests run fine.

@miguelcobain Any ideas?

:confused:

**Comment by miguelcobain** [comment]
If had some success creating custom DOM like this in another app:

```js
var component = Ember.Component.create({
  container: this.container,
  layoutName: templateName,
  model: data
});

component.createElement();
// access `component.element`
```

Of course, `layoutName` should be interchangeable with `layout`.
Also, updating Ember version could be useful. Just try to merge master into this branch. Master is updated.

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-cli-selectize/commit/47bfcaa9a8470b3f3b845a6e7b64f9272a4cad71

**Pull request closed without merging**
