### PR TITLE
Allow passing sort options to selectize

### PR DESCRIPTION
**Pull request by davekaro**
I'd like sorting abilities to pass on to selectize. I think defaulting to the label value is a good start. Might be useful to also allow specifying a property on the content objects?

### CODE REVIEW

**Comment by miguelcobain** [comment]
This might not be very trivial at the moment.

This is the object we pass to selectize:
```javascript
data = {
  label : get(obj, get(this,'_labelPath')),
  value : get(obj, get(this,'_valuePath')),
  data : obj
};
```

This represents our app object in an array. So selectize only has access to `label`,`value` and that reference to the original object. I don't think selectize/sifter allows you to pass `data.someProperty` for sorting purposes. Even if it would, it would know how to call Ember `get` for example.
However, you could work that. Maybe passing to selectize the sort property the user asks.

Something like:
```javascript
data = {
  label : get(obj, get(this,'_labelPath')),
  value : get(obj, get(this,'_valuePath')),
  data : obj
};
if(get(this,'sortField')){
  data[get(this,'sortField')] = get(obj, get(this,'sortField'));
}
```

Hmm. Might work.

**Comment by miguelcobain** [comment]
Update this PR please.

**Comment by davekaro** [comment]
Good point. I updated to allow specifying any property on the content objects. I wondered if we should keep the convention of "content.property" for passing in the option?

Question: Why pass the `data` key to selectize at all? I'm not aware of any reason selectize would need/use that.

**Comment by miguelcobain** [comment]
Selectize doesn't need it, you're right.
However at that time I thought I could need the original value. For example, check `_onItemAdd` callback.
Currently we just do a `find` in our original object array. It could be faster to just use that `data` reference directly somehow. In any case I ended up not using it.

Regarding your PR, I just noticed that selectize also accepts an array of values for sorting.
Might be a good idea to accept an array of fields as well. However I also like the simplicity of letting users just set a simple field in their templates.

To be clear, we should accept
 - `sortField` = "someField" **and** `sortDirection` = "asc"
 - `sortField` = an array of objects `[{ field: 'someField', direction: 'asc' }, {/*...*/}]`, following the same standard as selectize, ignoring `sortDirection` in this case

What are your thoughts on this?

**Comment by davekaro** [comment]
Yes I think supporting the array option is good. Added code for that too. If this looks good, I can add docs to the README also

**Comment by miguelcobain** [comment]
This looks good to me.

**Comment by davekaro** [comment]
Ok should be all set with docs too

**Comment by miguelcobain** [comment]
Perfect! Thanks.

**Pull request merged**
