### PR TITLE
Ember-cli 0.2.3 & ember-try

### PR DESCRIPTION
**Pull request by truenorth**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Any idea why this is failing?

Ember-cli is complaining about missing npm packages.

**Comment by truenorth** [comment]
Looks like a stale NPM cache issue.
https://travis-ci.org/miguelcobain/ember-cli-selectize/builds/58930305#L1054-L1057

**Comment by truenorth** [comment]
@miguelcobain could you try to clear the caches on this travis-ci project and re-run my PR build?
http://docs.travis-ci.com/user/caching/#Clearing-Caches

**Comment by miguelcobain** [comment]
@truenorth Thank you for this!

**Pull request merged**
